export const environmentalImpacts = [
  {
    id: 1,
    title: 'SmartX Watch',
    productId: 'DPP-101',
    impactType: 'Social',
    originCountry: 'Japan',
    status: 'Active',
    lastUpdated: '2025-11-01',
  },
  {
    id: 2,
    title: 'EcoDrive Scooter',
    productId: 'DPP-102',
    impactType: 'Power',
    originCountry: 'Germany',
    status: 'Pending',
    lastUpdated: '2025-10-28',
  },
  {
    id: 3,
    title: 'AeroDrone X2',
    productId: 'DPP-103',
    impactType: 'Animal',
    originCountry: 'USA',
    status: 'Active',
    lastUpdated: '2025-11-05',
  },
  {
    id: 4,
    title: 'EcoBag Backpack',
    productId: 'DPP-104',
    impactType: 'Social',
    originCountry: 'India',
    status: 'Active',
    lastUpdated: '2025-11-10',
  },
  {
    id: 5,
    title: 'SolarHome Panel',
    productId: 'DPP-105',
    impactType: 'Power',
    originCountry: 'China',
    status: 'Pending',
    lastUpdated: '2025-11-08',
  },
  {
    id: 6,
    title: 'BioPet Toy Set',
    productId: 'DPP-106',
    impactType: 'Animal',
    originCountry: 'USA',
    status: 'Active',
    lastUpdated: '2025-11-12',
  },
]
